{% set name = 'Triumvirate' %}
{% set version = environ.get('GIT_DESCRIBE_TAG', 'v0.3.0') %}

package:
  name: "{{ name|lower }}"
  version: {{ version|trim('v') }}

source:
  git_url: ../../../
  # git_rev: v0.3.0
  # path: ../../../

build:
  number: 0
  script:
    # Use Conda-provided compiler.
    - export PY_CXX=$CXX
    # Enforce OpenMP support.
    - export PY_OMP=1
    # Default to LLVM OpenMP on macOS.
    - export PY_CXXFLAGS_OMP="-Xpreprocessor -fopenmp"  # [osx]
    - export PY_LDFLAGS_OMP="-lomp"                     # [osx]
    - {{ PYTHON }} -m pip install . -vvv
  script_env:
    - PY_BUILD_PARALLEL="-j"

requirements:
  build:
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - numpy >=1.17                        # [build_platform != target_platform]
    - {{ compiler('cxx') }}
  host:
    - python
    - pip >=19.1
    # Use Conda-provided libraries.
    - gsl >=2.7
    - fftw >=3
    - libgomp                 # [linux]
    - llvm-openmp             # [osx]
    - setuptools >=61.0.0
    - setuptools_scm >=6.4.0
    - cython >=0.25
    - extension-helpers
    - numpy >=1.17
  run:
    - python >=3.8
    - {{ pin_compatible("numpy") }}
    - scipy
    - sympy
    - astropy >=4.2
    - pyyaml >4

test:
  requires:
    - pytest  # [build_platform == target_platform]
  source_files:
    - tests/
  commands:
    - pytest --full-trace --verbose --capture=no --runslow tests/  # [build_platform == target_platform]

about:
  home: https://mikeswang.github.io/Triumvirate
  license: "GNU General Public License v3 or later (GPLv3+)"
  license_family: GPL3
  license_file: LICENCE
  summary: "Three-point clustering measurements in large-scale structure analyses."
  doc_url: https://triumvirate.readthedocs.io
  dev_url: https://github.com/MikeSWang/Triumvirate

extra:
  recipe-maintainers:
    - MikeSWang
